# Generated by Django 4.1.7 on 2023-10-17 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_clap_article_claps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Responses",
            new_name="Response",
        ),
        migrations.AlterModelOptions(
            name="response",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Response",
                "verbose_name_plural": "Responses",
            },
        ),
    ]
